version: '3.8'

services:
  jenkins-dashboard:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_USERNAME=${JENKINS_USERNAME}
      - JENKINS_API_TOKEN=${JENKINS_API_TOKEN}
      - JENKINS_TEST_MODE=${JENKINS_TEST_MODE:-false}
    restart: unless-stopped 